# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import ucsmodel_pb2 as proto_dot_ucsmodel__pb2


class UCSStub(object):
    """
    Services, see this repo readme for more details
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getList = channel.unary_unary(
                '/ucs.UCS/getList',
                request_serializer=proto_dot_ucsmodel__pb2.ListRequest.SerializeToString,
                response_deserializer=proto_dot_ucsmodel__pb2.ListData.FromString,
                )
        self.getAsset = channel.unary_stream(
                '/ucs.UCS/getAsset',
                request_serializer=proto_dot_ucsmodel__pb2.AssetRequest.SerializeToString,
                response_deserializer=proto_dot_ucsmodel__pb2.StaticContent.FromString,
                )
        self.getMetaPack = channel.unary_stream(
                '/ucs.UCS/getMetaPack',
                request_serializer=proto_dot_ucsmodel__pb2.MetaPackRequest.SerializeToString,
                response_deserializer=proto_dot_ucsmodel__pb2.StaticContent.FromString,
                )
        self.addStaticContent = channel.unary_unary(
                '/ucs.UCS/addStaticContent',
                request_serializer=proto_dot_ucsmodel__pb2.StaticContentAddRequest.SerializeToString,
                response_deserializer=proto_dot_ucsmodel__pb2.Cid.FromString,
                )
        self.forgetStaticContent = channel.unary_unary(
                '/ucs.UCS/forgetStaticContent',
                request_serializer=proto_dot_ucsmodel__pb2.Cid.SerializeToString,
                response_deserializer=proto_dot_ucsmodel__pb2.Cid.FromString,
                )
        self.restoreStaticContent = channel.unary_unary(
                '/ucs.UCS/restoreStaticContent',
                request_serializer=proto_dot_ucsmodel__pb2.Cid.SerializeToString,
                response_deserializer=proto_dot_ucsmodel__pb2.Cid.FromString,
                )


class UCSServicer(object):
    """
    Services, see this repo readme for more details
    """

    def getList(self, request, context):
        """Get cid values in a list
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAsset(self, request, context):
        """Get all content associated with a class id / cid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMetaPack(self, request, context):
        """Specific case of getAsset for previews only, you may get all available metadata here
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addStaticContent(self, request, context):
        """Publish content and get back Cid value (=hash) from the storage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def forgetStaticContent(self, request, context):
        """Tmp solution to remove (hide) cid from registry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def restoreStaticContent(self, request, context):
        """Tmp solution to restore previously hidden cid in registry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UCSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getList': grpc.unary_unary_rpc_method_handler(
                    servicer.getList,
                    request_deserializer=proto_dot_ucsmodel__pb2.ListRequest.FromString,
                    response_serializer=proto_dot_ucsmodel__pb2.ListData.SerializeToString,
            ),
            'getAsset': grpc.unary_stream_rpc_method_handler(
                    servicer.getAsset,
                    request_deserializer=proto_dot_ucsmodel__pb2.AssetRequest.FromString,
                    response_serializer=proto_dot_ucsmodel__pb2.StaticContent.SerializeToString,
            ),
            'getMetaPack': grpc.unary_stream_rpc_method_handler(
                    servicer.getMetaPack,
                    request_deserializer=proto_dot_ucsmodel__pb2.MetaPackRequest.FromString,
                    response_serializer=proto_dot_ucsmodel__pb2.StaticContent.SerializeToString,
            ),
            'addStaticContent': grpc.unary_unary_rpc_method_handler(
                    servicer.addStaticContent,
                    request_deserializer=proto_dot_ucsmodel__pb2.StaticContentAddRequest.FromString,
                    response_serializer=proto_dot_ucsmodel__pb2.Cid.SerializeToString,
            ),
            'forgetStaticContent': grpc.unary_unary_rpc_method_handler(
                    servicer.forgetStaticContent,
                    request_deserializer=proto_dot_ucsmodel__pb2.Cid.FromString,
                    response_serializer=proto_dot_ucsmodel__pb2.Cid.SerializeToString,
            ),
            'restoreStaticContent': grpc.unary_unary_rpc_method_handler(
                    servicer.restoreStaticContent,
                    request_deserializer=proto_dot_ucsmodel__pb2.Cid.FromString,
                    response_serializer=proto_dot_ucsmodel__pb2.Cid.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ucs.UCS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UCS(object):
    """
    Services, see this repo readme for more details
    """

    @staticmethod
    def getList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ucs.UCS/getList',
            proto_dot_ucsmodel__pb2.ListRequest.SerializeToString,
            proto_dot_ucsmodel__pb2.ListData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAsset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ucs.UCS/getAsset',
            proto_dot_ucsmodel__pb2.AssetRequest.SerializeToString,
            proto_dot_ucsmodel__pb2.StaticContent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getMetaPack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ucs.UCS/getMetaPack',
            proto_dot_ucsmodel__pb2.MetaPackRequest.SerializeToString,
            proto_dot_ucsmodel__pb2.StaticContent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def addStaticContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ucs.UCS/addStaticContent',
            proto_dot_ucsmodel__pb2.StaticContentAddRequest.SerializeToString,
            proto_dot_ucsmodel__pb2.Cid.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def forgetStaticContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ucs.UCS/forgetStaticContent',
            proto_dot_ucsmodel__pb2.Cid.SerializeToString,
            proto_dot_ucsmodel__pb2.Cid.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def restoreStaticContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ucs.UCS/restoreStaticContent',
            proto_dot_ucsmodel__pb2.Cid.SerializeToString,
            proto_dot_ucsmodel__pb2.Cid.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
